#!/usr/bin/env python3
"""
GMAIL APP PASSWORD SETUP GUIDE
==============================
Your Gmail authentication failed. Here's how to fix it:
"""

print("🔧 GMAIL EMAIL AUTHENTICATION FIX")
print("=" * 50)
print()
print("❌ Current Issue: Username and Password not accepted")
print("🔑 Solution: Use Gmail App Password instead of regular password")
print()
print("📋 STEPS TO FIX EMAIL:")
print("=" * 30)
print("1. Go to: https://myaccount.google.com/security")
print("2. Enable 2-Step Verification (if not already enabled)")
print("3. Go to 'App passwords' section")
print("4. Generate new app password for 'Mail'")
print("5. Copy the 16-character app password")
print("6. Replace EMAIL_PASSWORD in .env with the app password")
print()
print("🔄 CURRENT .ENV EMAIL SETTINGS:")
print("EMAIL_USERNAME=rizwanpatelmalipatel@gmail.com")
print("EMAIL_PASSWORD=cbdbsrmebffcwrg  ← REPLACE THIS WITH APP PASSWORD")
print()
print("✅ AFTER FIXING:")
print("EMAIL_USERNAME=rizwanpatelmalipatel@gmail.com")
print("EMAIL_PASSWORD=your-16-char-app-password-here")
print()
print("📱 ALTERNATIVE: Use a different email service")
print("   - Outlook/Hotmail")
print("   - Yahoo Mail")
print("   - Or any SMTP service")
print()
print("🚨 IMPORTANT: The app password will be 16 characters like: abcd efgh ijkl mnop")

print("\n" + "=" * 50)
print("📅 GOOGLE CALENDAR API FIX")
print("=" * 30)
print("❌ Current Issue: Service not authenticated")
print("🔑 Solution: Set up Google Calendar API OAuth2")
print()
print("📋 STEPS TO FIX CALENDAR:")
print("1. Go to: https://console.cloud.google.com/")
print("2. Create new project or select existing one")
print("3. Enable Google Calendar API")
print("4. Create credentials (OAuth 2.0 client ID)")
print("5. Download credentials.json file")
print("6. Put credentials.json in your backend folder")
print("7. Run authentication flow")
print()
print("🔄 OR: Skip calendar for now and test email only")

print("\n" + "=" * 50)
print("⚡ QUICK TEST OPTIONS:")
print("1. Fix Gmail app password → Test email")
print("2. Use different email service → Test email") 
print("3. Skip calendar → Test automation without calendar")
print()
print("🎯 PRIORITY: Fix email first, then calendar")
print("📧 Email is more critical for candidate notifications")
